pipelines:
  branches:
    master:
      - step:
          name: Get repository latest changes
          script:
            # Clone the repository onto the server
            - git clone git@bitbucket.org:pacific-wp/astro-theme.git
            - git checkout master
          artifacts:
            # Save repositories code
            - ./astro-theme
      - step:
          name: Deploy to Production
          script:
            # SSH into the server and remove the existing folder
            # - ssh $MKTCASINOS_USER@$MKTCASINOS_SERVER "rm -rf applications/szkhyquxps/public_html/the-beach && mkdir applications/szkhyquxps/public_html/the-beach"

            # Update the remote with rsync
            - rsync -zrSlh --stats ./* $MKTCASINOS_USER@$MKTCASINOS_SERVER:applications/szkhyquxps/public_html/the-beach

            # Copy .htaccess file to the server
            - scp .htaccess $MKTCASINOS_USER@$MKTCASINOS_SERVER:applications/szkhyquxps/public_html/the-beach/

            # Make the ./restart_server.sh executable
            - ssh $MKTCASINOS_USER@$MKTCASINOS_SERVER "chmod +x applications/szkhyquxps/public_html/the-beach/restart_server.sh"

            # Check if the server is running before stopping it
            - |
              if ssh $MKTCASINOS_USER@$MKTCASINOS_SERVER 'lsof -i :4321'; then
                ssh $MKTCASINOS_USER@$MKTCASINOS_SERVER 'kill -9 $(lsof -t -i:4321)'
              fi

            # Build the project on the server > /dev/null 2>&1 &
            - ssh $MKTCASINOS_USER@$MKTCASINOS_SERVER "cd applications/szkhyquxps/public_html/the-beach && npm install && npm run build && php restart_server.php"

            # Send message to MatterMost
            - COMMIT_MESSAGE=$(git log --format=%B -n 1 $BITBUCKET_COMMIT)
            - COMMIT_DATE=$(git log -n 1 --pretty=format:'%ci' $BITBUCKET_COMMIT)
            - COMMIT_AUTHOR=$(git log -n 1 --pretty=format:'%an' $BITBUCKET_COMMIT)
            - >
              curl -d '{
                  "channel": "wp-team-activity",
                  "username": "Bitbucket Pipelines",
                  "text": "New commit deployed to #SlotsParadise **master** branch on ```Astro slotsparadise``` with the following message: \n ```\n'"$COMMIT_MESSAGE"' \nEnv: AstroSlotsParadise\nDate: '"$COMMIT_DATE"'\nAuthor: '"$COMMIT_AUTHOR"'\n ```"
                }' -H "Content-Type: application/json" -X POST https://matter.dblexchange.com/hooks/t34yjuo6a3refeeafr3itdauge